export const mockLibraries = [
  {
    id: 'lib-1',
    libraryName: "The Scholar's Nook",
    address: '123 Connaught Place',
    city: 'Delhi',
    state: 'Delhi',
    pincode: '110001',
    country: 'India',
    googleMapLink: 'https://maps.google.com/?q=Delhi',
    photos: [
        'https://placehold.co/600x400/E2D9FF/5D3EBC?text=Nook+Photo+1',
        'https://placehold.co/600x400/E2D9FF/5D3EBC?text=Nook+Photo+2',
    ],
    totalSeats: 50,
    openingTime: '08:00',
    closingTime: '22:00',
    contactNumber: '9876543210',
    whatsAppNumber: '9876543210',
    description: 'A quiet and modern study space in the heart of the city, perfect for focused work.',
    facilities: ['WiFi', 'Air Conditioning', 'Drinking Water', 'Power Backup', 'Locker Facility'], // Added Locker Facility to match data
    isActive: true,
    managerName: 'Rajesh Kumar',
    managerPhone: '9988776655',
    managerEmail: 'rajesh@scholarsnook.com',
    onboardingStatus: 'PRICING_COMPLETED',
    reviewStatus: 'PENDING',
    area: 'Connaught Place',
    librarianId: 'librarian-123',
    librarian: { firstName: 'Alice', lastName: 'Wonder' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),

    // --- MODIFIED & ADDED SECTIONS ---
    timeSlots: [
      { id: 1, name: 'Morning Shift', startTime: '08:00', endTime: '16:00', hours: '8.00', slotPools: ['Morning', 'Afternoon'] },
      { id: 2, name: 'Evening Shift', startTime: '16:00', endTime: '22:00', hours: '6.00', slotPools: ['Evening'] },
    ],
    lockers: [
      { id: 1, lockerType: 'Small', numberOfLockers: '20', charge: '300', description: 'For personal belongings' },
    ],
    plans: [
      { id: 1, hours: '8', planType: 'Fixed', timeSlotId: '1', slotPools: [], monthlyFee: '2500', description: 'Full day access (Morning)' },
      { id: 2, hours: '6', planType: 'Fixed', timeSlotId: '2', slotPools: [], monthlyFee: '2000', description: 'Evening access only' },
    ],
    seatConfigurations: [
      { id: 1, seatNumbers: '1-20', seatType: 'Fixed', attachLocker: true, lockerTypeId: '1', applicablePlanIds: ['1', '2'] },
      { id: 2, seatNumbers: '21-50', seatType: 'Float', attachLocker: false, lockerTypeId: '', applicablePlanIds: [] },
    ],
    packageRules: [
       { id: 1, planId: '1', duration: 6, discount: '10' },
    ],
    offers: [],
  },
  {
    id: 'lib-2',
    libraryName: 'Silent Pages Study Hall',
    address: '456 Marine Drive',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400001',
    country: 'India',
    googleMapLink: 'https://maps.google.com/?q=Mumbai',
    photos: ['https://placehold.co/600x400/D1FAE5/065F46?text=Silent+Pages'],
    totalSeats: 100,
    openingTime: '09:00',
    closingTime: '21:00',
    contactNumber: '9876543211',
    whatsAppNumber: '9876543211',
    description: 'Spacious and serene environment for dedicated students and professionals.',
    facilities: ['WiFi', 'Air Conditioning', 'CCTV Security', 'Locker Facility'],
    isActive: true,
    managerName: 'Priya Singh',
    managerPhone: '9123456789',
    managerEmail: 'priya@silentpages.com',
    onboardingStatus: 'PRICING_COMPLETED',
    reviewStatus: 'APPROVED',
    area: 'Marine Drive',
    librarianId: 'librarian-123',
    librarian: { firstName: 'Alice', lastName: 'Wonder' },
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),

    // --- MODIFIED & ADDED SECTIONS ---
    timeSlots: [
       { id: 1, name: 'Full Day', startTime: '09:00', endTime: '21:00', hours: '12.00', slotPools: ['Morning', 'Afternoon', 'Evening'] },
    ],
    lockers: [], // Kept as empty, as in original
    plans: [
      { id: 1, hours: '12', planType: 'Float', timeSlotId: '', slotPools: ['Morning', 'Afternoon', 'Evening'], monthlyFee: '3000', description: 'All-inclusive monthly pass' },
    ],
    seatConfigurations: [],
    packageRules: [],
    offers: [],
  },
  {
    id: 'lib-3',
    libraryName: 'Read & Rise Library',
    address: '789 MG Road',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560001',
    country: 'India',
    googleMapLink: 'https://maps.google.com/?q=Bengaluru',
    photos: [],
    totalSeats: 75,
    openingTime: '07:00',
    closingTime: '23:00',
    contactNumber: '9876543212',
    whatsAppNumber: '9876543212',
    description: '24/7 access for the night owls and early birds.',
    facilities: ['WiFi', 'Power Backup', 'Printing/Photocopy'],
    isActive: false,
    managerName: 'Arjun Reddy',
    managerPhone: '9988771122',
    managerEmail: 'arjun@readrise.com',
    onboardingStatus: 'PRICING_COMPLETED',
    reviewStatus: 'REJECTED',
    area: 'MG Road',
    librarianId: 'librarian-456',
    librarian: { firstName: 'Bob', lastName: 'Builder' },
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    
    // --- MODIFIED & ADDED SECTIONS ---
    timeSlots: [],
    lockers: [],
    plans: [],
    seatConfigurations: [],
    packageRules: [],
    offers: [],
  },
  {
    id: 'lib-4',
    libraryName: 'The Cozy Corner',
    address: '101 FC Road',
    city: 'Pune',
    state: 'Maharashtra',
    pincode: '411001',
    country: 'India',
    googleMapLink: null,
    photos: [],
    totalSeats: 30,
    openingTime: '10:00',
    closingTime: '20:00',
    contactNumber: '9876543213',
    whatsAppNumber: null,
    description: 'A small, comfortable space for quiet reading.',
    facilities: ['WiFi', 'Drinking Water'],
    isActive: true,
    managerName: null,
    managerPhone: null,
    managerEmail: null,
    onboardingStatus: 'DETAILED_INFO_COMPLETED',
    reviewStatus: 'PENDING',
    area: 'FC Road',
    librarianId: 'librarian-456',
    librarian: { firstName: 'Bob', lastName: 'Builder' },
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 10).toISOString(),

    // --- MODIFIED & ADDED SECTIONS ---
    timeSlots: [],
    lockers: [],
    plans: [],
    seatConfigurations: [],
    packageRules: [],
    offers: [],
  },
];